"""roles_table

Revision ID: 28545cc10ce1
Revises: 9e5aead0a2d8
Create Date: 2025-09-22 13:08:07.915376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.auth.models import Role
from src.auth.schema import RoleEnum


# revision identifiers, used by Alembic.
revision: str = '28545cc10ce1'
down_revision: Union[str, Sequence[str], None] = '9e5aead0a2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###

    op.bulk_insert(
        Role.__table__,
            [
            {"id": 1, "name": RoleEnum.ADMIN.value},
            {"id": 2, "name": RoleEnum.USER.value},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
