"""22_09_25

Revision ID: 9e5aead0a2d8
Revises: 305f06f36acb
Create Date: 2025-09-22 11:55:18.468158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5aead0a2d8'
down_revision: Union[str, Sequence[str], None] = '305f06f36acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('contact', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('contact', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contact_phone'), 'contact', ['phone'], unique=False)
    op.create_foreign_key(None, 'contact', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_index(op.f('ix_contact_phone'), table_name='contact')
    op.drop_column('contact', 'owner_id')
    op.drop_column('contact', 'phone')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
